server:
  port: 8080
  tomcat:
    max-swallow-size: -1
  forward-headers-strategy: framework
  servlet:
    session:
      timeout: 20m

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/helpdesk?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      pool-name: HelpdeskHikariPool
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 3000
      idle-timeout: 60000
      max-lifetime: 1800000
  thymeleaf:
    cache: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 30MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

app:
  upload:
    dir: uploads
  mail:
    verification-code-expire-minutes: 5
    sender-email: ${GOOGLE_SENDER_EMAIL}
    oauth:
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
      refresh-token: ${GOOGLE_OAUTH_REFRESH_TOKEN}

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.helpdesk.user.domain

logging:
  level:
    "[com.helpdesk]": debug
    "[org.springframework.security]": debug
    "[com.zaxxer.hikari]": debug